const themes = {
  borderRadius: '6px',
  padding: '20px',
  colors: {
    yellow: '#FFE000',
    white: '#fafafa',
    lightYellow: '#FFE235',
    darkYellow: '#CC9F02',
    darkerYellow: '#AD8700',
    black: '#221D1D',
    lightBlue: '#06ABEC',
    blue: '#337AB7',
    lightGrey: '#6C6C6C',
    lighterGrey: '#B7B7B7',
    grey: '#3c3c3c',
    lightest: '#FFFFFF',
    darkGrey: '#1e2021',
    warningRed: '#FF3232',
    lightOrange: '#FFE9A9',
    lighterYellow: '#FFF2CB',
    green: '#BCF285',
    lightBrown: '#FFF2CB',
  },
  nav: {
    startup: 'StartupPage',
    login: 'LoginPage',
    signup: 'SignupPage',
    home: 'HomePage',
    profile: 'ProfilePage',
    editProfile: 'EditProfilePage',
    task: 'TaskPage',
  },
}
export type MyTheme = typeof themes
export default themes
